### PR TITLE
Switch from X, Y back to Pose(s)

### PR DESCRIPTION
**Pull request by ia74**
I think having the encoders as a Pose allow for more customizability & better performance. 
My team also uses it this way, and without it being a Pose we can't use Pedro.

I also bumped the version to 1.0.2 if that's okay.

### CODE REVIEW

**Comment by ia74** [comment]
if this gets accepted, ill also go rewrite the documentation & make a pull there for this

**Comment by rowan-mcalpin** [comment]
Even when it was a pose, Pedro only used one component from each pose, so there's no performance difference involved

**Comment by ia74** [comment]
ooohhh okay i see

**Comment by rowan-mcalpin** [comment]
It should be fairly trivial to use the strafe x and parallel y values from your poses for each deadwheel

**Comment by ia74** [comment]
then it makes sense as to why it is how it is

**Pull request closed without merging**
